name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.103'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'      
      - name: Setup note
        uses: actions/setup-node@v2
        with:
          node-version: '14'      
      - run: dotnet build 
      - run: dotnet test 
      - run: npm install
        working-directory: ./DotnetTemplate.Web
      - run: npm run build
        working-directory: ./DotnetTemplate.Web
      - run: npm t 
        working-directory: ./DotnetTemplate.Web
      - run: npm run lint
        working-directory: ./DotnetTemplate.Web