name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.103'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.3'
      - run: dotnet build <DevOps-Course-Workshop-Module-07-Learners>
      - run: dotnet test <DevOps-Course-Workshop-Module-07-Learners>
      - run: npm t <DevOps-Course-Workshop-Module-07-Learners>
      - run: npm run lint <DevOps-Course-Workshop-Module-07-Learners>